#pragma once

// Generated by tools/cycles_path_trace_schema.py. Do not edit.

#include <cstdint>
#include <string_view>

namespace psycles::luisa_backend::path_trace_schema {

inline constexpr std::string_view name{"psycles.cycles-path-trace"};
inline constexpr std::uint32_t version = 1u;
inline constexpr std::uint32_t global_slot_count = 8u;
inline constexpr std::uint32_t event_slot_count = 72u;
inline constexpr std::uint32_t max_events = 4u;
inline constexpr std::uint32_t max_closures = 8u;
inline constexpr std::uint32_t slot_count = 296u;

enum class GlobalSlot : std::uint32_t {
    header = 0u,
    rng = 1u,
    filter = 2u,
    lens_time = 3u,
    ray_p = 4u,
    ray_d = 5u,
    ray_range = 6u,
    reserved = 7u,
};

enum class EventSlot : std::uint32_t {
    state_depth = 0u,
    state_lobes = 1u,
    state_visibility = 2u,
    state_flags = 3u,
    throughput = 4u,
    ray_p = 5u,
    ray_d = 6u,
    ray_range = 7u,
    isect_coord = 8u,
    isect_id = 9u,
    surface_meta = 10u,
    surface_p = 11u,
    surface_ng = 12u,
    surface_n = 13u,
    random_scalars = 14u,
    random_light = 15u,
    random_bsdf = 16u,
    light_meta = 17u,
    light_id = 18u,
    light_pdf = 19u,
    light_d = 20u,
    light_p = 21u,
    light_ng = 22u,
    light_eval = 23u,
    closure_pick = 24u,
    closure_random = 25u,
    closure_weight = 26u,
    closure_n = 27u,
    bsdf_meta = 28u,
    bsdf_wo = 29u,
    bsdf_eval = 30u,
    bsdf_roughness_eta = 31u,
    post_depth = 32u,
    post_throughput = 33u,
    post_ray_p = 34u,
    post_ray_d = 35u,
    post_flags = 36u,
    post_mis = 37u,
    surface_flags = 38u,
    post_visibility = 39u,
    light_shader = 40u,
    reserved_41 = 41u,
    reserved_42 = 42u,
    reserved_43 = 43u,
    reserved_44 = 44u,
    reserved_45 = 45u,
    reserved_46 = 46u,
    reserved_47 = 47u,
    closure_base = 48u,
};

[[nodiscard]] constexpr std::uint32_t index(
    GlobalSlot slot) noexcept {
    return static_cast<std::uint32_t>(slot);
}

[[nodiscard]] constexpr std::uint32_t index(
    std::uint32_t event,
    EventSlot slot) noexcept {
    return global_slot_count + event * event_slot_count +
           static_cast<std::uint32_t>(slot);
}

[[nodiscard]] constexpr std::uint32_t closure_index(
    std::uint32_t event,
    std::uint32_t closure,
    std::uint32_t field) noexcept {
    return index(event, EventSlot::closure_base) + closure * 3u +
           field;
}

}// namespace psycles::luisa_backend::path_trace_schema
