#include <psycles/compiler/cycles_svm_bytecode.h>

#include "cycles_svm_internal.h"

#include <array>
#include <bit>
#include <cmath>
#include <cstdint>
#include <cstdlib>
#include <iostream>
#include <span>
#include <string_view>
#include <vector>

#include <luisa/luisa-compute.h>

namespace {

using namespace luisa::compute;
using namespace psycles::compiler::cycles_svm;
namespace svm_detail = psycles::luisa_backend::cycles_svm::detail;

constexpr auto a_offset = std::uint32_t{0u};
constexpr auto b_offset = std::uint32_t{12u};
constexpr auto c_offset = std::uint32_t{24u};
constexpr auto param1_offset = std::uint32_t{36u};
constexpr auto value_offset = std::uint32_t{44u};
constexpr auto vector_offset = std::uint32_t{48u};
constexpr auto vector_math_word_count = static_cast<std::uint32_t>(
    sizeof(SVMNodeVectorMath) / sizeof(std::uint32_t));
constexpr auto operation_count =
    static_cast<std::size_t>(NODE_VECTOR_MATH_ROUND) + 1u;
static_assert(vector_math_word_count == 12u);
static_assert(operation_count == 30u);

struct OracleCase {
  float plain_value;
  luisa::float3 plain_vector;
  luisa::float3 dual_value;
  luisa::float3 dual_vector;
  luisa::float3 dual_vector_dx;
  luisa::float3 dual_vector_dy;
};

// Generated by compiling Cycles 5.2.1's svm_vector_math template directly
// for float3 and dual3. These values cover every NodeVectorMathType with the
// exact same input duals used by the device kernel below. Tolerance is
// deliberately arithmetic rather than bit-exact: the regression protects
// dispatch, typed payload, output liveness, and Cycles' derivative rules.
constexpr std::array<OracleCase, operation_count> oracle{{
    {0.0f, {1.75f, 0.75f, -0.400000006f}, {0.0f, 0.0f, 0.0f},
     {1.75f, 0.75f, -0.400000006f},
     {0.0600000024f, -0.120000005f, 0.170000002f},
     {0.0200000033f, -0.0299999993f, 0.129999995f}},
    {0.0f, {0.75f, -2.25f, 1.20000005f}, {0.0f, 0.0f, 0.0f},
     {0.75f, -2.25f, 1.20000005f},
     {0.140000001f, -0.280000001f, -0.0699999928f},
     {-0.159999996f, 0.0899999961f, 0.0900000036f}},
    {0.0f, {0.625f, -1.125f, -0.320000023f}, {0.0f, 0.0f, 0.0f},
     {0.625f, -1.125f, -0.320000023f},
     {3.7252903e-9f, -0.360000014f, 0.00799999759f},
     {0.0775000006f, 0.0899999961f, -0.0799999982f}},
    {0.0f, {2.5f, -0.5f, -0.5f}, {0.0f, 0.0f, 0.0f},
     {2.5f, -0.5f, -0.5f},
     {0.399999976f, -0.106666669f, -0.137500003f},
     {-0.590000033f, 0.0f, -0.149999991f}},
    {0.0f, {0.0f, 1.20000005f, 2.25f}, {0.0f, 0.0f, 0.0f},
     {0.0f, 1.20000005f, 2.25f},
     {-0.0369999856f, -0.0609999895f, 0.319999993f},
     {-0.179999992f, 0.0100000016f, -0.127499998f}},
    {0.0f, {-0.130573258f, -0.391719759f, 0.208917215f},
     {0.0f, 0.0f, 0.0f},
     {-0.130573258f, -0.391719759f, 0.208917215f},
     {-0.0452724248f, -0.188046575f, 0.0578116775f},
     {-0.0146432975f, 0.0422484614f, -0.0193987545f}},
    {0.0f, {1.51114655f, 0.0334394574f, -0.0178343952f},
     {0.0f, 0.0f, 0.0f},
     {1.51114655f, 0.0334394574f, -0.0178343952f},
     {0.190544859f, 0.176093146f, -0.0656233579f},
     {-0.0407134145f, -0.054496944f, 0.148797512f}},
    {-0.820000052f, {0.0f, 0.0f, 0.0f},
     {-0.820000052f, -0.352000028f, 0.0874999911f},
     {0.0f, 0.0f, 0.0f}, {0.0f, 0.0f, 0.0f}, {0.0f, 0.0f, 0.0f}},
    {2.65800667f, {0.0f, 0.0f, 0.0f},
     {2.65800667f, 0.244920388f, -0.080699563f},
     {0.0f, 0.0f, 0.0f}, {0.0f, 0.0f, 0.0f}, {0.0f, 0.0f, 0.0f}},
    {1.51162171f, {0.0f, 0.0f, 0.0f},
     {1.51162171f, 0.195154652f, -0.0436617173f},
     {0.0f, 0.0f, 0.0f}, {0.0f, 0.0f, 0.0f}, {0.0f, 0.0f, 0.0f}},
    {0.0f, {0.8125f, -0.487499982f, 0.25999999f},
     {0.0f, 0.0f, 0.0f}, {0.8125f, -0.487499982f, 0.25999999f},
     {0.0962499976f, -0.148749992f, 0.0425000004f},
     {-0.0892499983f, 0.0457499996f, 0.0574999973f}},
    {0.0f, {0.82692647f, -0.496155858f, 0.26461646f},
     {0.0f, 0.0f, 0.0f}, {0.82692647f, -0.496155858f, 0.26461646f},
     {-0.0406044424f, -0.0682530925f, -0.0010856837f},
     {-0.0224229172f, 0.00551525597f, 0.0804127157f}},
    {0.0f, {1.0f, -1.5f, 0.800000012f}, {0.0f, 0.0f, 0.0f},
     {1.0f, -1.5f, 0.800000012f},
     {-0.0799999982f, -0.0799999982f, -0.119999997f},
     {0.180000007f, 0.0599999987f, -0.0199999996f}},
    {0.0f, {1.0f, -1.0f, 0.0f}, {0.0f, 0.0f, 0.0f},
     {1.0f, -1.0f, 0.0f}, {0.0f, 0.0f, 0.0f}, {0.0f, 0.0f, 0.0f}},
    {0.0f, {2.0f, 0.0f, 1.0f}, {0.0f, 0.0f, 0.0f},
     {2.0f, 0.0f, 1.0f}, {0.0f, 0.0f, 0.0f}, {0.0f, 0.0f, 0.0f}},
    {0.0f, {0.25f, -0.75f, 0.400000006f}, {0.0f, 0.0f, 0.0f},
     {0.25f, -0.75f, 0.400000006f},
     {0.100000001f, -0.200000003f, 0.0500000007f},
     {-0.0700000003f, 0.0299999993f, 0.109999999f}},
    {0.0f, {0.25f, 0.25f, 0.400000006f}, {0.0f, 0.0f, 0.0f},
     {0.25f, 0.25f, 0.400000006f},
     {0.100000001f, -0.200000003f, 0.0500000007f},
     {-0.0700000003f, 0.0299999993f, 0.109999999f}},
    {0.0f, {1.25f, 0.75f, 0.400000006f}, {0.0f, 0.0f, 0.0f},
     {1.25f, 0.75f, 0.400000006f},
     {0.100000001f, 0.200000003f, 0.0500000007f},
     {-0.0700000003f, -0.0299999993f, 0.109999999f}},
    {0.0f, {0.5f, -0.75f, -0.800000012f}, {0.0f, 0.0f, 0.0f},
     {0.5f, -0.75f, -0.800000012f},
     {-0.0399999991f, -0.200000003f, 0.119999997f},
     {0.0900000036f, 0.0299999993f, 0.0199999996f}},
    {0.0f, {1.25f, 1.5f, 0.400000006f}, {0.0f, 0.0f, 0.0f},
     {1.25f, 1.5f, 0.400000006f},
     {0.100000001f, 0.0799999982f, 0.0500000007f},
     {-0.0700000003f, -0.0599999987f, 0.109999999f}},
    {0.0f, {0.449999928f, 0.849999964f, 0.399999976f},
     {0.0f, 0.0f, 0.0f}, {0.449999928f, 0.849999964f, 0.399999976f},
     {0.170000002f, -0.180000007f, 0.049999997f},
     {-0.179999992f, -0.169999987f, 0.109999999f}},
    {0.0f, {0.948984623f, -0.681638777f, 0.389418334f},
     {0.0f, 0.0f, 0.0f}, {0.948984623f, -0.681638777f, 0.389418334f},
     {0.0315322392f, -0.146337777f, 0.0460530482f},
     {-0.0220725667f, 0.0219506659f, 0.101316705f}},
    {0.0f, {0.315322369f, 0.731688857f, 0.921060979f},
     {0.0f, 0.0f, 0.0f}, {0.315322369f, 0.731688857f, 0.921060979f},
     {-0.0948984623f, -0.136327758f, -0.0194709171f},
     {0.0664289221f, 0.0204491634f, -0.0428360179f}},
    {0.0f, {3.00956964f, -0.931596458f, 0.422793239f},
     {0.0f, 0.0f, 0.0f}, {3.00956964f, -0.931596458f, 0.422793239f},
     {1.00575101f, -0.373574406f, 0.0589377061f},
     {-0.704025686f, 0.0560361594f, 0.129662946f}},
    {0.0f, {0.666758955f, -0.924723148f, 0.493185699f},
     {0.0f, 0.0f, 0.0f}, {0.666758955f, -0.924723148f, 0.493185699f},
     {0.138724446f, -0.0796230957f, -0.0417821072f},
     {-0.133738562f, 0.00847340375f, 0.0808786377f}},
    {0.0f, {1.25f, -0.75f, 0.400000006f}, {0.0f, 0.0f, 0.0f},
     {1.25f, -0.75f, 0.400000006f},
     {0.100000001f, -0.200000003f, 0.0500000007f},
     {-0.0700000003f, 0.0299999993f, 0.109999999f}},
    {0.0f, {0.324999988f, -0.425000012f, 0.879999995f},
     {0.0f, 0.0f, 0.0f}, {0.324999988f, -0.425000012f, 0.879999995f},
     {0.0300000031f, -0.290000021f, -0.0820000023f},
     {0.057500001f, 0.129999995f, -0.0199999996f}},
    {0.0f, {1.11803401f, 0.0f, 2.08138299f}, {0.0f, 0.0f, 0.0f},
     {1.11803401f, 0.0f, 2.08138299f},
     {0.0347420797f, 0.0f, -0.43699652f},
     {-0.00885156356f, 0.0f, -0.496047288f}},
    {0.0f, {1.0f, -1.0f, 1.0f}, {0.0f, 0.0f, 0.0f},
     {1.0f, -1.0f, 1.0f}, {0.0f, 0.0f, 0.0f}, {0.0f, 0.0f, 0.0f}},
    {0.0f, {1.0f, -1.0f, 0.0f}, {0.0f, 0.0f, 0.0f},
     {1.0f, -1.0f, 0.0f}, {0.0f, 0.0f, 0.0f}, {0.0f, 0.0f, 0.0f}},
}};

template <typename T>
void append_payload(std::vector<std::uint32_t> &words, const T &payload) {
  const auto encoded = std::bit_cast<
      std::array<std::uint32_t, sizeof(T) / sizeof(std::uint32_t)>>(payload);
  words.insert(words.end(), encoded.begin(), encoded.end());
}

[[nodiscard]] auto vector_math_kernel() {
  return Kernel1D<Buffer<std::uint32_t>, Buffer<luisa::float4>,
                  Buffer<std::uint32_t>>{
      [](BufferUInt words, BufferFloat4 output, BufferUInt cursors) noexcept {
        const UInt index = dispatch_x();
        svm_detail::Stack plain_stack;
        svm_detail::stack_store_float3(plain_stack, a_offset,
                                       make_float3(1.25f, -0.75f, 0.4f));
        svm_detail::stack_store_float3(plain_stack, b_offset,
                                       make_float3(0.5f, 1.5f, -0.8f));
        svm_detail::stack_store_float3(plain_stack, c_offset,
                                       make_float3(-0.3f, 0.7f, 1.2f));
        svm_detail::stack_store_float(plain_stack, param1_offset, 0.65f);
        UInt plain_cursor = index * vector_math_word_count;
        svm_detail::Cursor plain_words{words, plain_cursor};
        svm_detail::node_vector_math(plain_words, plain_stack, false);
        output.write(index * 4u,
                     make_float4(svm_detail::stack_load_float3(
                                     plain_stack, vector_offset),
                                 svm_detail::stack_load_float(
                                     plain_stack, value_offset)));

        svm_detail::Stack dual_stack;
        svm_detail::stack_store_dual3(
            dual_stack, a_offset,
            {.val = make_float3(1.25f, -0.75f, 0.4f),
             .dx = make_float3(0.1f, -0.2f, 0.05f),
             .dy = make_float3(-0.07f, 0.03f, 0.11f)});
        svm_detail::stack_store_dual3(
            dual_stack, b_offset,
            {.val = make_float3(0.5f, 1.5f, -0.8f),
             .dx = make_float3(-0.04f, 0.08f, 0.12f),
             .dy = make_float3(0.09f, -0.06f, 0.02f)});
        svm_detail::stack_store_dual3(
            dual_stack, c_offset,
            {.val = make_float3(-0.3f, 0.7f, 1.2f),
             .dx = make_float3(0.03f, 0.07f, -0.09f),
             .dy = make_float3(-0.02f, 0.04f, 0.06f)});
        svm_detail::stack_store_dual1(
            dual_stack, param1_offset,
            {.val = 0.65f, .dx = 0.025f, .dy = -0.035f});
        UInt dual_cursor = index * vector_math_word_count;
        svm_detail::Cursor dual_words{words, dual_cursor};
        svm_detail::node_vector_math(dual_words, dual_stack, true);
        output.write(index * 4u + 1u,
                     make_float4(svm_detail::stack_load_float3(
                                     dual_stack, vector_offset),
                                 svm_detail::stack_load_float(
                                     dual_stack, value_offset)));
        output.write(index * 4u + 2u,
                     make_float4(svm_detail::stack_load_float3(
                                     dual_stack, vector_offset + 3u),
                                 svm_detail::stack_load_float(
                                     dual_stack, value_offset + 1u)));
        output.write(index * 4u + 3u,
                     make_float4(svm_detail::stack_load_float3(
                                     dual_stack, vector_offset + 6u),
                                 svm_detail::stack_load_float(
                                     dual_stack, value_offset + 2u)));
        cursors.write(index * 2u,
                      plain_cursor - index * vector_math_word_count);
        cursors.write(index * 2u + 1u,
                      dual_cursor - index * vector_math_word_count);
      }};
}

[[nodiscard]] bool near(float actual, float expected,
                        float tolerance = 2.0e-4f) noexcept {
  return std::isfinite(actual) &&
         std::abs(actual - expected) <=
             tolerance * std::max(1.0f, std::abs(expected));
}

[[nodiscard]] bool near(luisa::float3 actual, luisa::float3 expected) noexcept {
  return near(actual.x, expected.x) && near(actual.y, expected.y) &&
         near(actual.z, expected.z);
}

} // namespace

int main(int argc, char **argv) {
  const auto backend = std::string_view{argc > 1 ? argv[1] : "hip"};
  std::vector<std::uint32_t> words;
  words.reserve(operation_count * vector_math_word_count);
  for (auto operation = std::size_t{}; operation < operation_count;
       ++operation) {
    append_payload(
        words,
        SVMNodeVectorMath{
            .math_type = static_cast<NodeVectorMathType>(operation),
            .a = input_float3(static_cast<SVMStackOffset>(a_offset)),
            .b = input_float3(static_cast<SVMStackOffset>(b_offset)),
            .c = input_float3(static_cast<SVMStackOffset>(c_offset)),
            .param1 = input_float(static_cast<SVMStackOffset>(param1_offset)),
            .value_offset = static_cast<SVMStackOffset>(value_offset),
            .vector_offset = static_cast<SVMStackOffset>(vector_offset),
            ._pad = {0u, 0u}});
  }

  Context context{argv[0]};
  auto device = context.create_device(backend);
  auto stream = device.create_stream();
  auto word_buffer = device.create_buffer<std::uint32_t>(words.size());
  auto output_buffer =
      device.create_buffer<luisa::float4>(operation_count * 4u);
  auto cursor_buffer =
      device.create_buffer<std::uint32_t>(operation_count * 2u);
  auto shader = device.compile(
      vector_math_kernel(),
      ShaderOption{.enable_cache = false, .enable_fast_math = false});
  std::array<luisa::float4, operation_count * 4u> actual{};
  std::array<std::uint32_t, operation_count * 2u> cursors{};
  stream << word_buffer.copy_from(luisa::span{words})
         << shader(word_buffer, output_buffer, cursor_buffer)
                .dispatch(operation_count)
         << output_buffer.copy_to(luisa::span{actual})
         << cursor_buffer.copy_to(luisa::span{cursors}) << synchronize();

  for (auto operation = std::size_t{}; operation < operation_count;
       ++operation) {
    const auto &expected = oracle[operation];
    const auto plain = actual[operation * 4u];
    const auto dual = actual[operation * 4u + 1u];
    const auto dual_dx = actual[operation * 4u + 2u];
    const auto dual_dy = actual[operation * 4u + 3u];
    if (!near(plain.xyz(), expected.plain_vector) ||
        !near(plain.w, expected.plain_value) ||
        !near(dual.xyz(), expected.dual_vector) ||
        !near(luisa::float3{dual.w, dual_dx.w, dual_dy.w},
              expected.dual_value) ||
        !near(dual_dx.xyz(), expected.dual_vector_dx) ||
        !near(dual_dy.xyz(), expected.dual_vector_dy) ||
        cursors[operation * 2u] != vector_math_word_count ||
        cursors[operation * 2u + 1u] != vector_math_word_count) {
      std::cerr << "Cycles Vector Math oracle mismatch on " << backend
                << ", operation=" << operation << '\n';
      return EXIT_FAILURE;
    }
  }
  return EXIT_SUCCESS;
}
