#include <psycles/compiler/cycles_nishita.h>
#include <psycles/compiler/cycles_svm_compiler.h>
#include <psycles/luisa/cycles_svm.h>

#include "cycles_svm_image_sampling.h"
#include "cycles_svm_internal.h"
#include "cycles_svm_scene_image.h"
#include "luisa_cycles_svm_test_kernel_globals.h"

#include <array>
#include <bit>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <iostream>
#include <string_view>
#include <utility>
#include <vector>

#include <luisa/luisa-compute.h>

namespace {

using namespace luisa::compute;
using namespace psycles::compiler::cycles_svm;
namespace device_svm = psycles::luisa_backend::cycles_svm;
namespace svm_detail = psycles::luisa_backend::cycles_svm::detail;
namespace scene_detail = psycles::luisa_backend::detail;
using SceneImageBinding = scene_detail::CyclesSvmImageBindingGpu;

constexpr auto direction_offset = std::uint32_t{0u};
constexpr auto color_offset = std::uint32_t{3u};
constexpr auto payload_word_count = std::uint32_t{14u};

struct SkyProbe {
  const char *name;
  luisa::float3 direction;
  luisa::float3 cycles_radiance;
};

// External camera-ray oracle from Blender/Cycles 5.2.1, generated by
// tools/probe_cycles_world.py from `nishita_diffuse_transport`. These are raw
// scene-linear Combined values; no Psycles reference evaluator is involved.
constexpr std::array probes{
    SkyProbe{"near_zenith",
             {0.0009999974863603711f, 0.0019999949727207422f,
              0.9999974966049194f},
             {1.4131922721862793f, 1.9320071935653687f,
              3.1922097206115723f}},
    SkyProbe{"north_horizon",
             {0.0f, 1.0f, 9.999999747378752e-05f},
             {3.131779909133911f, 3.191657304763794f,
              2.6847965717315674f}},
    SkyProbe{"east_horizon",
             {1.0f, 0.0f, 9.999999747378752e-05f},
             {3.6323184967041016f, 3.3270251750946045f,
              2.5429816246032715f}},
    SkyProbe{"ground", {0.0f, 0.0f, -1.0f}, {0.0f, 0.0f, 0.0f}},
    SkyProbe{"sun",
             {0.30090752243995667f, -0.5211870670318604f,
              0.7986355423927307f},
             {776768.25f, 640431.5f, 503210.4375f}},
};

class SkyKernelGlobals final
    : public psycles::test_support::DefaultCyclesSvmKernelGlobals {
private:
  Expr<BindlessArray> _textures;
  Expr<Buffer<SceneImageBinding>> _bindings;

public:
  SkyKernelGlobals(Expr<BindlessArray> textures,
                   Expr<Buffer<SceneImageBinding>> bindings) noexcept
      : _textures{std::move(textures)}, _bindings{std::move(bindings)} {}

  [[nodiscard]] Float4 kernel_image_interp_with_udim(
      device_svm::ShaderData &, Expr<std::int32_t> image_texture_id,
      const device_svm::Dual2 &uv) const noexcept override {
    return svm_detail::sample_scene_image_2d(
        _textures, _bindings, image_texture_id, uv);
  }
};

[[nodiscard]] device_svm::ShaderData make_shader_data() noexcept {
  const auto identity = make_float4x4(1.0f);
  return device_svm::ShaderData{
      make_float3(0.0f), make_float3(0.0f, 0.0f, 1.0f),
      make_float3(0.0f, 0.0f, 1.0f), make_float3(0.0f, 0.0f, -1.0f),
      device_svm::primitive_triangle, 0u, 0u, 0u, 0u, 0.2f, 0.3f, 0u,
      0.25f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f,
      make_float3(1.0f, 0.0f, 0.0f), make_float3(0.0f, 1.0f, 0.0f),
      identity, identity};
}

[[nodiscard]] Kernel1D<BindlessArray, Buffer<SceneImageBinding>,
                       Buffer<std::uint32_t>, Buffer<luisa::float3>,
                       Buffer<luisa::float4>, Buffer<std::uint32_t>>
make_probe_kernel() {
  return [](BindlessVar textures, BufferVar<SceneImageBinding> bindings,
            BufferUInt words, BufferFloat3 directions,
            BufferFloat4 output, BufferUInt cursors) noexcept {
    const UInt index = dispatch_x();
    $if(index < static_cast<std::uint32_t>(probes.size())) {
      svm_detail::Stack stack;
      svm_detail::stack_store_float3(
          stack, direction_offset, directions.read(index));
      auto shader_data = make_shader_data();
      const SkyKernelGlobals kernel_globals{textures, bindings};
      const device_svm::PathState path_state{0u, 0u};
      UInt cursor_offset = 0u;
      svm_detail::Cursor cursor{words, cursor_offset};
      svm_detail::node_tex_sky(
          cursor, stack, kernel_globals, shader_data, path_state);
      output.write(index,
                   make_float4(svm_detail::stack_load_float3(
                                   stack, color_offset),
                               1.0f));
      cursors.write(index, cursor_offset);
    };
  };
}

[[nodiscard]] std::array<std::uint32_t, payload_word_count>
make_payload(const NishitaImageBinding &binding) {
  constexpr auto authored_sun_size = 0.01745329238474369f;
  constexpr auto sun_rotation = 3.6651914755450647f;
  const auto sun = precompute_nishita_sun(binding, authored_sun_size);
  return {
      static_cast<std::uint32_t>(NODE_SKY_SINGLE_SCATTERING),
      direction_offset | (color_offset << 8u),
      std::bit_cast<std::uint32_t>(sun.pixel_bottom.x),
      std::bit_cast<std::uint32_t>(sun.pixel_bottom.y),
      std::bit_cast<std::uint32_t>(sun.pixel_bottom.z),
      std::bit_cast<std::uint32_t>(sun.pixel_top.x),
      std::bit_cast<std::uint32_t>(sun.pixel_top.y),
      std::bit_cast<std::uint32_t>(sun.pixel_top.z),
      std::bit_cast<std::uint32_t>(binding.sun_elevation()),
      std::bit_cast<std::uint32_t>(sun_rotation),
      std::bit_cast<std::uint32_t>(authored_sun_size),
      std::bit_cast<std::uint32_t>(1.0f),
      std::bit_cast<std::uint32_t>(sun.earth_intersection_angle),
      0u,
  };
}

[[nodiscard]] bool close(float actual, float expected) noexcept {
  // Native texture filtering and backend transcendental instructions need not
  // reproduce a host float at one ULP. This gate rejects structural sky/LUT,
  // coordinate, sun-disc, and color-transform errors without trading device
  // performance for a bitwise oracle. The relative term is bounded to 0.125%,
  // including the CPU oracle versus native HIP/Vulkan transcendental and
  // linear-filter differences near the LUT's steep horizon and solar-disc
  // gradients.
  return std::isfinite(actual) && std::isfinite(expected) &&
         std::abs(actual - expected) <=
             1.0e-3f + 1.25e-3f * std::abs(expected);
}

[[nodiscard]] bool run(Device &device, Stream &stream,
                       std::string_view backend) {
  constexpr auto binding = NishitaImageBinding::encode(
      false, 0.9250245094299316f, 0.0f, 1.0f, 1.0f, 1.0f);
  const auto payload = make_payload(binding);
  const auto lut = precompute_nishita_texture(binding);
  std::vector<luisa::float4> pixels;
  pixels.reserve(nishita_texture_width * nishita_texture_height);
  for (auto index = std::size_t{};
       index < nishita_texture_width * nishita_texture_height; ++index) {
    pixels.emplace_back(lut[index * 4u], lut[index * 4u + 1u],
                        lut[index * 4u + 2u], lut[index * 4u + 3u]);
  }
  std::array<luisa::float3, probes.size()> directions{};
  for (auto index = std::size_t{}; index < probes.size(); ++index) {
    directions[index] = probes[index].direction;
  }
  constexpr std::array scene_bindings{
      scene_detail::make_cycles_svm_image_binding(
          0u, ImageInterpolation::linear, ImageExtension::extend)};

  auto image = device.create_image<float>(
      PixelStorage::FLOAT4, nishita_texture_width, nishita_texture_height);
  auto textures = device.create_bindless_array(1u);
  textures.emplace_on_update(0u, image, Sampler::linear_point_repeat());
  auto binding_buffer =
      device.create_buffer<SceneImageBinding>(scene_bindings.size());
  auto word_buffer = device.create_buffer<std::uint32_t>(payload.size());
  auto direction_buffer =
      device.create_buffer<luisa::float3>(directions.size());
  auto output_buffer = device.create_buffer<luisa::float4>(probes.size());
  auto cursor_buffer = device.create_buffer<std::uint32_t>(probes.size());
  auto shader = device.compile(
      make_probe_kernel(),
      ShaderOption{.enable_cache = false, .enable_fast_math = true});
  std::array<luisa::float4, probes.size()> output{};
  std::array<std::uint32_t, probes.size()> cursors{};
  stream << image.copy_from(luisa::span{pixels}) << textures.update()
         << binding_buffer.copy_from(luisa::span{scene_bindings})
         << word_buffer.copy_from(luisa::span{payload})
         << direction_buffer.copy_from(luisa::span{directions})
         << shader(textures, binding_buffer, word_buffer, direction_buffer,
                   output_buffer, cursor_buffer)
                .dispatch(static_cast<std::uint32_t>(probes.size()))
         << output_buffer.copy_to(luisa::span{output})
         << cursor_buffer.copy_to(luisa::span{cursors}) << synchronize();

  auto valid = true;
  for (auto index = std::size_t{}; index < probes.size(); ++index) {
    const auto actual = output[index];
    const auto expected = probes[index].cycles_radiance;
    if (cursors[index] != payload_word_count ||
        !close(actual.x, expected.x) || !close(actual.y, expected.y) ||
        !close(actual.z, expected.z)) {
      std::cerr << "Nishita " << probes[index].name << " mismatch on "
                << backend << ": actual={" << actual.x << ", " << actual.y
                << ", " << actual.z << "}, Cycles={" << expected.x << ", "
                << expected.y << ", " << expected.z << "}, cursor="
                << cursors[index] << '\n';
      valid = false;
    }
  }
  return valid;
}

} // namespace

int main(int argc, char **argv) {
  const auto backend = std::string_view{argc > 1 ? argv[1] : "hip"};
  Context context{argv[0]};
  auto device = context.create_device(backend);
  auto stream = device.create_stream();
  return run(device, stream, backend) ? EXIT_SUCCESS : EXIT_FAILURE;
}
