#include <psycles/luisa/cycles_closure.h>
#include <psycles/luisa/cycles_sample_mapping.h>
#include <psycles/luisa/cycles_svm.h>

#include "cycles_svm_microfacet_scattering.h"
#include "luisa_cycles_svm_test_kernel_globals.h"

#include <algorithm>
#include <array>
#include <cmath>
#include <cstdint>
#include <iostream>
#include <luisa/luisa-compute.h>

namespace {
using namespace luisa::compute;
namespace svm = psycles::luisa_backend::cycles_svm;
namespace detail = svm::detail;
namespace closure = psycles::luisa_backend::cycles_closure;
namespace mapping = psycles::luisa_backend::cycles_sample_mapping;

// Direct Cycles 5.2.1 HIP outputs, generated by
// tools/cycles_svm_microfacet_union_oracle.hip against the external source.
// Each scenario records wo/pdf, value, roughness/eta, and direct eval/pdf.
constexpr std::array expected{
    luisa::float4{0.0538457707f, -0.923459828f, 0.379898429f, 0.322688967f},
    luisa::float4{0.291490346f, 0.183629915f, 0.107035987f, 0.0f},
    luisa::float4{0.25f, 0.519999981f, 1.0f, 0.0f},
    luisa::float4{0.153498664f, 0.0964855403f, 0.055849541f, 0.157260075f},
    luisa::float4{0.554006159f, -0.0864906088f, 0.828007877f, 0.39190954f},
    luisa::float4{0.332471073f, 0.166235536f, 0.0415588841f, 0.0f},
    luisa::float4{0.419999987f, 0.180000007f, 1.0f, 0.0f},
    luisa::float4{0.146594241f, 0.0732971206f, 0.0183242802f, 0.172209039f},
    luisa::float4{0.445940465f, -0.345547944f, 0.825671971f, 0.305059999f},
    luisa::float4{0.270815164f, 0.170227513f, 0.0985336676f, 0.0f},
    luisa::float4{0.25f, 0.519999981f, 1.0f, 0.0f},
    luisa::float4{0.203464404f, 0.127892792f, 0.0740292594f, 0.229192838f},
    luisa::float4{-0.326281965f, -0.266029656f, 0.90706569f, 0.731684685f},
    luisa::float4{0.585347891f, 0.292674243f, 0.0731690079f, 0.0f},
    luisa::float4{0.419999987f, 0.180000007f, 1.0f, 0.0f},
    luisa::float4{0.180115908f, 0.0900579542f, 0.0225144885f, 0.225144878f}};

[[nodiscard]] auto union_kernel() {
  return Kernel1D<Buffer<std::uint32_t>, Buffer<luisa::float4>,
                  Buffer<std::uint32_t>>{
      [](BufferUInt inputs, BufferFloat4 output, BufferUInt labels) noexcept {
        const auto lane = dispatch_x();
        const auto scenario = inputs.read(lane);
        const auto f82 = (scenario & 1u) != 0u;
        const auto ggx = scenario < 2u;
        const auto normal = normalize(make_float3(0.2f, -0.3f, 1.0f));
        const auto incoming = normalize(make_float3(0.35f, -0.15f, 0.925f));
        const auto direct = normalize(make_float3(0.4f, 0.1f, 0.91f));
        const auto basis = mapping::make_orthonormals_tangent(
            normal, normalize(make_float3(0.9f, 0.2f, -0.1f)));
        svm::ClosurePool pool{2u};
        const auto allocation = pool.allocate(
            select(closure::type_microfacet_beckmann,
                   closure::type_microfacet_ggx, ggx), make_float3(1.0f));
        static_cast<void>(pool.allocate_extra(allocation, 1u));
        pool.set_normal(allocation.index, normal);
        pool.set_sample_weight(allocation.index, 1.0f);
        pool.set_microfacet_param(
            allocation.index,
            {.alpha_x = select(0.25f, 0.42f, f82),
             .alpha_y = select(0.52f, 0.18f, f82),
             .ior = 1.45f,
             .energy_scale = select(1.11f, 1.07f, f82),
             .fresnel_type = select(
                 static_cast<std::uint32_t>(svm::MicrofacetFresnel::conductor),
                 static_cast<std::uint32_t>(svm::MicrofacetFresnel::f82_tint), f82),
             .T = basis.tangent});
        $if(f82) {
          pool.set_fresnel_f82_tint(
              allocation.index,
              {.thin_film = {.thickness = 0.0f, .ior = 1.3f},
               .f0 = make_float3(0.8f, 0.4f, 0.1f),
               .b = make_float3(0.12f, -0.08f, 0.04f)});
        }
        $else {
          pool.set_fresnel_conductor(
              allocation.index,
              {.thin_film = {.thickness = 0.0f, .ior = 1.4f},
               .ior = make_float3(0.3f, 0.8f, 1.2f),
               .extinction = make_float3(3.0f, 2.0f, 1.5f)});
        };
        const psycles::test_support::DefaultCyclesSvmKernelGlobals globals;
        // One storage-backed view, independent of the runtime Fresnel tag.
        // The tag must be dispatched inside Fresnel, not around the entire
        // geometry/sampling algorithm. Unused payload rows stay uninitialized.
        const auto view = pool.microfacet(allocation.index);
        const auto random = select(make_float3(0.21f, 0.83f, 0.5f),
                                   make_float3(0.67f, 0.19f, 0.5f), f82);
        const auto record = [&](const detail::BsdfSample &sample,
                                const detail::BsdfEvaluation &eval) noexcept {
          output.write(lane * 4u, make_float4(sample.wo, sample.pdf));
          output.write(lane * 4u + 1u, make_float4(sample.value, 0.0f));
          output.write(lane * 4u + 2u,
                       make_float4(sample.sampled_roughness, sample.eta, 0.0f));
          output.write(lane * 4u + 3u, make_float4(eval.value, eval.pdf));
          labels.write(lane, sample.label);
        };
        $if(ggx) {
          record(detail::bsdf_microfacet_ggx_sample(
                     globals, view, normal, incoming, random),
                 detail::bsdf_microfacet_ggx_eval(globals, view, incoming, direct));
        }
        $else {
          record(detail::bsdf_microfacet_beckmann_sample(
                     globals, view, normal, incoming, random),
                 detail::bsdf_microfacet_beckmann_eval(globals, view, incoming, direct));
        };
      }};
}
} // namespace

int main(int argc, char **argv) {
  if (argc != 2) { return 2; }
  Context context{argv[0]};
  auto device = context.create_device(argv[1]);
  auto stream = device.create_stream();
  constexpr auto count = 64u;
  std::array<std::uint32_t, count> scenarios{};
  for (auto i = 0u; i < count; ++i) { scenarios[i] = (i * 3u) % 4u; }
  auto inputs = device.create_buffer<std::uint32_t>(count);
  auto output = device.create_buffer<luisa::float4>(count * 4u);
  auto labels = device.create_buffer<std::uint32_t>(count);
  const auto shader = device.compile(
      union_kernel(), ShaderOption{.enable_cache = false, .enable_fast_math = true});
  std::array<luisa::float4, count * 4u> actual{};
  std::array<std::uint32_t, count> actual_labels{};
  stream << inputs.copy_from(scenarios.data())
         << shader(inputs, output, labels).dispatch(count)
         << output.copy_to(actual.data())
         << labels.copy_to(actual_labels.data()) << synchronize();
  for (auto i = 0u; i < count; ++i) {
    for (auto row = 0u; row < 4u; ++row) {
      for (auto channel = 0u; channel < 4u; ++channel) {
        const auto value = actual[i * 4u + row][channel];
        const auto oracle = expected[scenarios[i] * 4u + row][channel];
        if (!std::isfinite(value) ||
            std::abs(value - oracle) > 2.0e-4f * std::max(1.0f, std::abs(oracle))) {
          std::cerr << "scenario " << scenarios[i] << " row " << row
                    << " channel " << channel << ": " << value
                    << " != Cycles " << oracle << '\n';
          return 1;
        }
      }
    }
    if (actual_labels[i] != (closure::label_reflect | closure::label_glossy)) {
      std::cerr << "Incorrect Cycles reflection/glossy label\n";
      return 1;
    }
  }
  std::cout << "Cycles microfacet tagged-union regression passed\n";
}
