#!/usr/bin/env python3
"""Validate and report Psycles coverage of Blender's Cycles shader nodes.

The Blender RNA inventory is versioned separately. This file contains the
implementation decision for every Cycles-applicable node type. Nodes not named
in a device set are deliberately reported as pending; they are never treated
as supported by default. ``--require-complete`` is the release gate and stays
red until every Cycles node has a verified Luisa implementation.
"""

from __future__ import annotations

import argparse
import json
import math
import pathlib
import sys
from typing import Any


# These nodes have focused Blender Cycles/Psycles linear-pass probes covering
# their complete exposed semantics. Probe reports are generated by
# ``run_cycles_shader_probes.py``.
CYCLES_VERIFIED = {
    "BACKGROUND",
    "BRIGHTCONTRAST",
    "BSDF_TRANSPARENT",
    "CLAMP",
    "COMBINE_COLOR",
    "EMISSION",
    "GAMMA",
    "RGB",
    "RGBTOBW",
    "SEPARATE_COLOR",
    "TEX_WHITE_NOISE",
    "VALUE",
}

# These nodes execute in the Luisa graph interpreter, but still need dedicated
# Cycles linear-EXR probes before they can move to ``cycles_verified``.
DEVICE_IMPLEMENTED_UNVERIFIED = {
    "ADD_SHADER",
    "BSDF_DIFFUSE",
    "MIX_SHADER",
    "TEX_NOISE",
}

# These nodes have a device implementation with known missing modes, inputs, or
# exact Cycles math. Keeping this list separate prevents "works in Lone Monk"
# from being mistaken for full node support.
DEVICE_PARTIAL = {
    "BSDF_GLOSSY",
    "BSDF_PRINCIPLED",
    "BUMP",
    "CURVE_RGB",
    "HUE_SAT",
    "INVERT",
    "LAYER_WEIGHT",
    "LIGHT_PATH",
    "MAPPING",
    "MATH",
    "MIX",
    "NEW_GEOMETRY",
    "NORMAL_MAP",
    "OBJECT_INFO",
    "PARTICLE_INFO",
    "TEX_BRICK",
    "TEX_COORD",
    "TEX_GRADIENT",
    "TEX_IMAGE",
    "TEX_SKY",
    "UVMAP",
    "VALTORGB",
    "VERTEX_COLOR",
}

# Output nodes select a graph domain/root and do not become device instructions.
STRUCTURAL_ADAPTER = {
    "OUTPUT_MATERIAL",
    "OUTPUT_WORLD",
}

COMPLETE_STATUSES = {
    "cycles_verified",
    "structural_adapter",
}


def _arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "inventory",
        type=pathlib.Path,
        help="versioned cycles-shader-nodes JSON",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="emit the complete machine-readable report",
    )
    parser.add_argument(
        "--probe-baselines",
        type=pathlib.Path,
        help=(
            "recorded Cycles/Psycles probe metrics; defaults to the "
            "versioned file beside the inventory"
        ),
    )
    parser.add_argument(
        "--require-complete",
        action="store_true",
        help="fail while any Cycles node is partial, unverified, or pending",
    )
    return parser.parse_args()


def _validate_verified_baselines(
    inventory: dict[str, Any],
    path: pathlib.Path,
) -> None:
    with path.open(encoding="utf-8") as source:
        baselines = json.load(source)
    if baselines.get("schema") != (
        "psycles.cycles-shader-probe-baselines.v1"
    ):
        raise ValueError("unsupported shader-probe baseline schema")
    if baselines.get("blender_version") != inventory["blender_version"]:
        raise ValueError(
            "shader-probe baseline Blender version does not match "
            "the node inventory"
        )
    verified = baselines.get("verified")
    if not isinstance(verified, dict):
        raise ValueError("shader-probe baseline verified must be an object")
    recorded = set(verified)
    if recorded != CYCLES_VERIFIED:
        missing = sorted(CYCLES_VERIFIED - recorded)
        stale = sorted(recorded - CYCLES_VERIFIED)
        raise ValueError(
            "verified-node baseline mismatch; missing="
            + ",".join(missing)
            + "; stale="
            + ",".join(stale)
        )
    for node_type, probe in verified.items():
        if not isinstance(probe.get("probe"), str):
            raise ValueError(f"{node_type} has no probe name")
        max_rmse = probe.get("max_rmse", 1.0e-6)
        if (
            not isinstance(max_rmse, (int, float))
            or not math.isfinite(max_rmse)
            or max_rmse < 0.0
        ):
            raise ValueError(f"{node_type} has invalid max_rmse")
        passes = probe.get("passes")
        if not isinstance(passes, dict) or not passes:
            raise ValueError(f"{node_type} has no recorded passes")
        for pass_name, metrics in passes.items():
            rmse = metrics.get("rmse")
            if (
                not isinstance(rmse, (int, float))
                or not math.isfinite(rmse)
                or rmse > max_rmse
            ):
                raise ValueError(
                    f"{node_type}/{pass_name} has unverified RMSE {rmse}"
                )


def _status(node: dict[str, Any]) -> tuple[str, str]:
    applicability = node["applicability"]
    node_type = node.get("node_type")
    if applicability != "cycles":
        return applicability, "outside the Cycles device-node support target"
    if node_type in STRUCTURAL_ADAPTER:
        return (
            "structural_adapter",
            "handled as graph domain/root selection",
        )
    if node_type in CYCLES_VERIFIED:
        return (
            "cycles_verified",
            "verified by focused Cycles/Psycles linear-pass probes",
        )
    if node_type in DEVICE_IMPLEMENTED_UNVERIFIED:
        return (
            "device_implemented_unverified",
            "runs in Luisa; dedicated Cycles node probe still required",
        )
    if node_type in DEVICE_PARTIAL:
        return (
            "device_partial",
            "runs in Luisa with explicitly tracked missing Cycles semantics",
        )
    return "pending", "no supported Luisa lowering yet"


def _report(inventory: dict[str, Any]) -> dict[str, Any]:
    if inventory.get("schema") != (
        "psycles.cycles-shader-node-inventory.v1"
    ):
        raise ValueError("unsupported shader-node inventory schema")
    nodes = inventory.get("nodes")
    if not isinstance(nodes, list):
        raise ValueError("inventory nodes must be an array")

    known_types = {
        node.get("node_type")
        for node in nodes
        if node.get("applicability") == "cycles"
    }
    declared = (
        CYCLES_VERIFIED
        | DEVICE_IMPLEMENTED_UNVERIFIED
        | DEVICE_PARTIAL
        | STRUCTURAL_ADAPTER
    )
    stale = sorted(declared - known_types)
    if stale:
        raise ValueError(
            "coverage registry references absent node types: "
            + ", ".join(stale)
        )

    rows: list[dict[str, Any]] = []
    counts: dict[str, int] = {}
    cycles_total = 0
    complete = 0
    seen: set[str] = set()
    for node in nodes:
        bl_idname = node["bl_idname"]
        if bl_idname in seen:
            raise ValueError(f"duplicate bl_idname: {bl_idname}")
        seen.add(bl_idname)
        status, note = _status(node)
        counts[status] = counts.get(status, 0) + 1
        if node["applicability"] == "cycles":
            cycles_total += 1
            complete += int(status in COMPLETE_STATUSES)
        rows.append(
            {
                "bl_idname": bl_idname,
                "node_type": node.get("node_type"),
                "applicability": node["applicability"],
                "status": status,
                "note": note,
            }
        )

    return {
        "schema": "psycles.cycles-shader-node-coverage.v1",
        "blender_version": inventory["blender_version"],
        "inventory_node_count": len(nodes),
        "cycles_node_count": cycles_total,
        "complete_node_count": complete,
        "counts": dict(sorted(counts.items())),
        "nodes": rows,
    }


def main() -> int:
    arguments = _arguments()
    with arguments.inventory.open(encoding="utf-8") as source:
        inventory = json.load(source)
    baseline_path = arguments.probe_baselines
    if baseline_path is None:
        version = str(inventory["blender_version"]).split()[0]
        baseline_path = arguments.inventory.with_name(
            f"cycles-shader-probe-baselines-{version}.json"
        )
    _validate_verified_baselines(inventory, baseline_path)
    report = _report(inventory)

    if arguments.json:
        print(json.dumps(report, indent=2, sort_keys=True))
    else:
        counts = ", ".join(
            f"{name}={count}"
            for name, count in report["counts"].items()
        )
        print(
            f"Cycles shader nodes for Blender "
            f"{report['blender_version']}: "
            f"{report['complete_node_count']}/"
            f"{report['cycles_node_count']} complete; {counts}"
        )

    if arguments.require_complete:
        incomplete = [
            node
            for node in report["nodes"]
            if node["applicability"] == "cycles"
            and node["status"] not in COMPLETE_STATUSES
        ]
        if incomplete:
            print(
                f"coverage gate failed: {len(incomplete)} Cycles nodes "
                "are not verified",
                file=sys.stderr,
            )
            return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
