set(PSYCLES_LUISA_SOURCES
    src/luisa/graph_surface.cpp
    src/luisa/graph_surface_closures.cpp
    src/luisa/graph_surface_emission.cpp
    src/luisa/graph_surface_implementation.cpp
    src/luisa/graph_surface_physical_closures.cpp
    src/luisa/bssrdf_closure_component.cpp
    src/luisa/subsurface_exit_closure_component.cpp
    src/luisa/surface_closure_blocks.cpp
    src/luisa/surface_closure_visitor.cpp
    src/luisa/surface_closure_operations.cpp
    src/luisa/surface_closure_evaluation.cpp
    src/luisa/surface_closure_set.cpp
    src/luisa/surface_closure_evaluator.cpp
    src/luisa/surface_closure_sampling_core.cpp
    src/luisa/surface_closure_sampling.cpp
    src/luisa/microfacet_glass_component.cpp
    src/luisa/principled_base_component.cpp
    src/luisa/principled_layer_component.cpp
    src/luisa/graph_surface_scattering.cpp
    src/luisa/graph_surface_state.cpp
    src/luisa/graph_surface_value_expression.cpp
    src/luisa/graph_surface_values.cpp
    src/luisa/graph_surface_value_context.cpp
    src/luisa/graph_surface_value_image.cpp
    src/luisa/graph_surface_value_math.cpp
    src/luisa/graph_surface_value_normal.cpp
    src/luisa/graph_surface_value_wave.cpp
    src/luisa/graph_surface_value_voronoi.cpp
    src/luisa/graph_surface_value_procedural.cpp
    src/luisa/cycles_wave.cpp
    src/luisa/cycles_voronoi.cpp
    src/luisa/heterogeneous_volume_candidate.cpp
    src/luisa/heterogeneous_volume_collision.cpp
    src/luisa/heterogeneous_volume_guiding.cpp
    src/luisa/heterogeneous_volume_reservoir.cpp
    src/luisa/heterogeneous_volume_segment.cpp
    src/luisa/heterogeneous_volume_shadow.cpp
    src/luisa/heterogeneous_volume_tracking.cpp
    src/luisa/heterogeneous_volume_transmittance.cpp
    src/luisa/homogeneous_volume_segment.cpp
    src/luisa/homogeneous_volume_transport.cpp
    src/luisa/volume_scatter_probability.cpp
    src/luisa/volume_direct_sampling.cpp
    src/luisa/area_light_sampling.cpp
    src/luisa/triangle_light_sampling.cpp
    src/luisa/path_kernel_area_light.cpp
    src/luisa/volume_analytic_light_sampling.cpp
    src/luisa/volume_light_interval.cpp
    src/luisa/volume_guiding.cpp
    src/luisa/stacked_volume.cpp
    src/luisa/volume_majorant_hierarchy.cpp
    src/luisa/volume_majorant_overlap.cpp
    src/luisa/volume_majorant_prepass.cpp
    src/luisa/volume_majorant_traversal.cpp
    src/luisa/volume_phase_set.cpp
    src/luisa/volume_shadow_interval.cpp
    src/luisa/volume_stack.cpp)

set(PSYCLES_LUISA_RUNTIME_SOURCES
    src/adapter/blender_graph_lower_closures.cpp
    src/adapter/blender_graph_lower_inputs.cpp
    src/adapter/blender_graph_lower_procedural.cpp
    src/adapter/blender_graph_lower_values.cpp
    src/adapter/blender_graph_lowering_components.cpp
    src/adapter/blender_graph_normalizer.cpp
    src/adapter/blender_scene.cpp
    src/adapter/blender_scene_json.cpp
    src/luisa/path_tracer.cpp
    src/luisa/path_tracer_camera.cpp
    src/luisa/path_tracer_common.cpp
    src/luisa/path_tracer_environment.cpp
    src/luisa/path_tracer_generated_coordinates.cpp
    src/luisa/path_tracer_geometry.cpp
    src/luisa/path_kernel_background_event.cpp
    src/luisa/path_kernel_bounce_setup.cpp
    src/luisa/path_kernel_closest_event.cpp
    src/luisa/path_kernel_direct_light_trace.cpp
    src/luisa/path_kernel_emissive_triangle.cpp
    src/luisa/path_kernel_environment_light.cpp
    src/luisa/path_kernel_forward_light.cpp
    src/luisa/path_kernel_heterogeneous_volume.cpp
    src/luisa/path_kernel_nee_analytic.cpp
    src/luisa/path_kernel_nee_emissive_mesh.cpp
    src/luisa/path_kernel_nee_environment.cpp
    src/luisa/path_kernel_pipeline.cpp
    src/luisa/path_kernel_setup.cpp
    src/luisa/path_kernel_surface_geometry.cpp
    src/luisa/path_kernel_surface_scatter.cpp
    src/luisa/path_kernel_surface_shading.cpp
    src/luisa/path_kernel_subsurface.cpp
    src/luisa/subsurface_random_walk_component.cpp
    src/luisa/path_kernel_triangle_geometry.cpp
    src/luisa/path_kernel_triangle_primitive.cpp
    src/luisa/path_kernel_volume_boundary.cpp
    src/luisa/path_kernel_volume_direct_light.cpp
    src/luisa/path_kernel_volume_environment_light.cpp
    src/luisa/path_kernel_volume_majorant_provider.cpp
    src/luisa/path_kernel_volume_mesh_light.cpp
    src/luisa/path_kernel_volume_point.cpp
    src/luisa/path_kernel_volume_random.cpp
    src/luisa/path_kernel_volume_segment.cpp
    src/luisa/path_kernel_volume_shadow.cpp
    src/luisa/path_kernel_volume_state.cpp
    src/luisa/path_tracer_kernel.cpp
    src/luisa/path_tracer_image_decode.cpp
    src/luisa/path_tracer_light_distribution.cpp
    src/luisa/path_tracer_lighting.cpp
    src/luisa/path_tracer_scene.cpp
    src/luisa/path_tracer_scene_geometry.cpp
    src/luisa/path_tracer_session.cpp
    src/luisa/path_tracer_surface_closure_evaluation.cpp
    src/luisa/path_tracer_surface_closure_sampling.cpp
    src/luisa/path_tracer_surfaces.cpp
    src/luisa/path_tracer_volume_capabilities.cpp
    src/luisa/path_tracer_volume_majorant_scene.cpp
    src/luisa/path_tracer_volume_metadata.cpp
    src/luisa/volume_guiding_filter.cpp)
