set(PSYCLES_LUISA_SOURCES
    src/luisa/cycles_bsdf_tables.cpp
    src/luisa/cycles_svm.cpp
    src/luisa/cycles_svm_ashikhmin_shirley.cpp
    src/luisa/cycles_svm_bsdf.cpp
    src/luisa/cycles_svm_surface_shader.cpp
    src/luisa/cycles_svm_dual_math.cpp
    src/luisa/cycles_svm_bump.cpp
    src/luisa/cycles_svm_bssrdf.cpp
    src/luisa/cycles_svm_hair.cpp
    src/luisa/cycles_svm_camera.cpp
    src/luisa/cycles_svm_closure.cpp
    src/luisa/cycles_svm_microfacet.cpp
    src/luisa/cycles_svm_microfacet_fresnel.cpp
    src/luisa/cycles_svm_microfacet_scattering.cpp
    src/luisa/cycles_svm_principled.cpp
    src/luisa/cycles_svm_principled_hair.cpp
    src/luisa/cycles_svm_principled_hair_chiang.cpp
    src/luisa/cycles_svm_principled_hair_huang.cpp
    src/luisa/cycles_svm_principled_hair_math.cpp
    src/luisa/cycles_svm_ray_portal.cpp
    src/luisa/cycles_svm_sheen.cpp
    src/luisa/cycles_svm_toon.cpp
    src/luisa/cycles_svm_simple_closure.cpp
    src/luisa/cycles_svm_color.cpp
    src/luisa/cycles_svm_convert.cpp
    src/luisa/cycles_svm_fresnel.cpp
    src/luisa/cycles_svm_image.cpp
    src/luisa/cycles_svm_info.cpp
    src/luisa/cycles_svm_ies.cpp
    src/luisa/cycles_svm_light_falloff.cpp
    src/luisa/cycles_svm_mapping.cpp
    src/luisa/cycles_svm_math.cpp
    src/luisa/cycles_svm_noise.cpp
    src/luisa/cycles_svm_gabor.cpp
    src/luisa/cycles_svm_voronoi.cpp
    src/luisa/cycles_svm_normal.cpp
    src/luisa/cycles_svm_primitive_attribute.cpp
    src/luisa/cycles_svm_procedural_texture.cpp
    src/luisa/cycles_svm_ramp.cpp
    src/luisa/cycles_svm_spectral.cpp
    src/luisa/cycles_svm_volume_attribute.cpp
    src/luisa/cycles_svm_stack.cpp
    src/luisa/cycles_svm_transform.cpp
    src/luisa/cycles_svm_texture_coordinate.cpp
    src/luisa/cycles_svm_triangle.cpp
    src/luisa/cycles_svm_attribute.cpp
    src/luisa/cycles_svm_value.cpp
    src/luisa/cycles_svm_vector.cpp
    src/luisa/cycles_svm_vector_math.cpp
    src/luisa/cycles_svm_vector_rotate.cpp
    src/luisa/cycles_svm_vector_transform.cpp
    src/luisa/cycles_svm_vertex_color.cpp
    src/luisa/cycles_svm_wireframe.cpp
    src/luisa/graph_surface.cpp
    src/luisa/graph_surface_closures.cpp
    src/luisa/graph_surface_emission.cpp
    src/luisa/graph_surface_implementation.cpp
    src/luisa/graph_surface_physical_closures.cpp
    src/luisa/bssrdf_closure_component.cpp
    src/luisa/subsurface_exit_closure_component.cpp
    src/luisa/surface_closure_blocks.cpp
    src/luisa/surface_closure_physical_blocks.cpp
    src/luisa/surface_closure_visitor.cpp
    src/luisa/surface_closure_operations.cpp
    src/luisa/surface_closure_reachability.cpp
    src/luisa/surface_physical_closure_component.cpp
    src/luisa/surface_closure_evaluation.cpp
    src/luisa/surface_closure_population.cpp
    src/luisa/surface_preparation_accumulator.cpp
    src/luisa/surface_closure_set.cpp
    src/luisa/surface_closure_evaluator.cpp
    src/luisa/surface_closure_sampling_core.cpp
    src/luisa/surface_closure_sampling.cpp
    src/luisa/microfacet_anisotropy.cpp
    src/luisa/metallic_closure_component.cpp
    src/luisa/sheen_closure_component.cpp
    src/luisa/hair_closure_component.cpp
    src/luisa/hair_closure_scattering.cpp
    src/luisa/microfacet_glass_component.cpp
    src/luisa/principled_base_component.cpp
    src/luisa/principled_diffuse_component.cpp
    src/luisa/principled_layer_component.cpp
    src/luisa/principled_metallic_component.cpp
    src/luisa/principled_specular_state.cpp
    src/luisa/thin_glass_component.cpp
    src/luisa/cycles_thin_film_table_5_2_1.cpp
    src/luisa/thin_film_fresnel.cpp
    src/luisa/thin_subsurface_component.cpp
    src/luisa/graph_surface_scattering.cpp
    src/luisa/graph_surface_state.cpp
    src/luisa/surface_bump.cpp
    src/luisa/surface_displacement.cpp
    src/luisa/surface_color_nodes.cpp
    src/luisa/surface_color_transforms.cpp
    src/luisa/surface_geometry_context.cpp
    src/luisa/surface_image_box.cpp
    src/luisa/surface_image_sampling.cpp
    src/luisa/surface_image_svm.cpp
    src/luisa/surface_light_falloff.cpp
    src/luisa/surface_math.cpp
    src/luisa/surface_map_range.cpp
    src/luisa/surface_mix.cpp
    src/luisa/surface_vector_math.cpp
    src/luisa/surface_normal_map.cpp
    src/luisa/surface_shader_table_evaluation.cpp
    src/luisa/surface_vector_mapping.cpp
    src/luisa/graph_surface_value_expression.cpp
    src/luisa/graph_surface_values.cpp
    src/luisa/graph_surface_value_context.cpp
    src/luisa/graph_surface_value_ambient_occlusion.cpp
    src/luisa/graph_surface_value_bump_expanded.cpp
    src/luisa/graph_surface_value_image.cpp
    src/luisa/graph_surface_value_math.cpp
    src/luisa/graph_surface_value_normal.cpp
    src/luisa/graph_surface_value_displacement.cpp
    src/luisa/graph_surface_value_magic.cpp
    src/luisa/graph_surface_value_wave.cpp
    src/luisa/graph_surface_value_voronoi.cpp
    src/luisa/graph_surface_value_procedural.cpp
    src/luisa/shader_table_data.cpp
    src/luisa/cycles_transform.cpp
    src/luisa/cycles_magic.cpp
    src/luisa/cycles_triangle_surface_component.cpp
    src/luisa/cycles_wave.cpp
    src/luisa/cycles_voronoi.cpp
    src/luisa/cycles_gabor.cpp
    src/luisa/curve_ribbon_component.cpp
    src/luisa/heterogeneous_volume_candidate.cpp
    src/luisa/heterogeneous_volume_collision.cpp
    src/luisa/heterogeneous_volume_guiding.cpp
    src/luisa/heterogeneous_volume_reservoir.cpp
    src/luisa/heterogeneous_volume_segment.cpp
    src/luisa/heterogeneous_volume_shadow.cpp
    src/luisa/heterogeneous_volume_tracking.cpp
    src/luisa/heterogeneous_volume_transmittance.cpp
    src/luisa/homogeneous_volume_segment.cpp
    src/luisa/homogeneous_volume_transport.cpp
    src/luisa/volume_scatter_probability.cpp
    src/luisa/volume_direct_sampling.cpp
    src/luisa/area_light_sampling.cpp
    src/luisa/triangle_light_sampling.cpp
    src/luisa/path_kernel_area_light.cpp
    src/luisa/volume_analytic_light_sampling.cpp
    src/luisa/volume_light_interval.cpp
    src/luisa/volume_guiding.cpp
    src/luisa/stacked_volume.cpp
    src/luisa/volume_majorant_hierarchy.cpp
    src/luisa/volume_majorant_overlap.cpp
    src/luisa/volume_majorant_prepass.cpp
    src/luisa/volume_majorant_traversal.cpp
    src/luisa/volume_phase_set.cpp
    src/luisa/volume_shadow_interval.cpp
    src/luisa/volume_stack.cpp)

set(PSYCLES_LUISA_RUNTIME_SOURCES
    src/adapter/blender_graph_lower_closures.cpp
    src/adapter/blender_graph_lower_inputs.cpp
    src/adapter/blender_graph_lower_procedural.cpp
    src/adapter/blender_graph_lower_values.cpp
    src/adapter/blender_graph_lowering_components.cpp
    src/adapter/blender_graph_normalizer.cpp
    src/adapter/blender_graph_texture_mapping.cpp
    src/adapter/blender_scene.cpp
    src/adapter/blender_scene_json.cpp
    src/luisa/path_tracer.cpp
    src/luisa/path_tracer_attribute_lookup.cpp
    src/luisa/path_tracer_analytic_light_scene.cpp
    src/luisa/path_tracer_camera.cpp
    src/luisa/path_tracer_bump.cpp
    src/luisa/path_tracer_color_transforms.cpp
    src/luisa/path_tracer_normal_maps.cpp
    src/luisa/path_tracer_shader_tables.cpp
    src/luisa/path_tracer_subsurface_scene.cpp
    src/luisa/path_tracer_ambient_occlusion_scene.cpp
    src/luisa/path_tracer_ambient_occlusion.cpp
    src/luisa/path_tracer_vector_mapping.cpp
    src/luisa/path_tracer_common.cpp
    src/luisa/path_tracer_curve_scene.cpp
    src/luisa/path_tracer_environment.cpp
    src/luisa/path_tracer_generated_coordinates.cpp
    src/luisa/path_tracer_geometry.cpp
    src/luisa/path_kernel_background_event.cpp
    src/luisa/path_kernel_background_portal.cpp
    src/luisa/path_kernel_bounce_random.cpp
    src/luisa/path_kernel_bounce_setup.cpp
    src/luisa/path_kernel_closest_event.cpp
    src/luisa/path_kernel_curve_geometry.cpp
    src/luisa/path_kernel_curve_primitive.cpp
    src/luisa/path_kernel_direct_light_queue.cpp
    src/luisa/path_kernel_direct_light_trace.cpp
    src/luisa/path_kernel_direct_light_task.cpp
    src/luisa/path_kernel_direct_light_transport.cpp
    src/luisa/path_kernel_emissive_triangle.cpp
    src/luisa/path_kernel_environment_light.cpp
    src/luisa/path_kernel_executor.cpp
    src/luisa/path_kernel_film.cpp
    src/luisa/path_kernel_forward_light.cpp
    src/luisa/path_kernel_heterogeneous_volume.cpp
    src/luisa/path_kernel_nee_analytic.cpp
    src/luisa/path_kernel_nee_emissive_mesh.cpp
    src/luisa/path_kernel_nee_environment.cpp
    src/luisa/path_kernel_pipeline.cpp
    src/luisa/path_kernel_primitive_material.cpp
    src/luisa/path_kernel_scene_traversal.cpp
    src/luisa/path_kernel_shadow_storage.cpp
    src/luisa/path_kernel_setup.cpp
    src/luisa/path_kernel_surface_geometry.cpp
    src/luisa/path_kernel_surface_primitive.cpp
    src/luisa/path_kernel_surface_queue.cpp
    src/luisa/path_kernel_surface_scatter.cpp
    src/luisa/path_kernel_surface_shading.cpp
    src/luisa/path_kernel_subsurface.cpp
    src/luisa/path_kernel_subsurface_intersection.cpp
    src/luisa/path_kernel_subsurface_state.cpp
    src/luisa/subsurface_random_walk_component.cpp
    src/luisa/path_kernel_triangle_geometry.cpp
    src/luisa/path_kernel_triangle_primitive.cpp
    src/luisa/path_kernel_volume_boundary.cpp
    src/luisa/path_kernel_volume_direct_light.cpp
    src/luisa/path_kernel_volume_environment_light.cpp
    src/luisa/path_kernel_volume_majorant_provider.cpp
    src/luisa/path_kernel_volume_mesh_light.cpp
    src/luisa/path_kernel_volume_point.cpp
    src/luisa/path_kernel_volume_random.cpp
    src/luisa/path_kernel_volume_segment.cpp
    src/luisa/path_kernel_volume_shadow.cpp
    src/luisa/path_kernel_volume_state.cpp
    src/luisa/path_tracer_kernel.cpp
    src/luisa/path_tracer_bsdf_tables.cpp
    src/luisa/path_tracer_image_decode.cpp
    src/luisa/path_tracer_light_distribution.cpp
    src/luisa/path_tracer_light_sampling_scene.cpp
    src/luisa/path_tracer_light_tree.cpp
    src/luisa/path_tracer_light_tree_importance.cpp
    src/luisa/path_tracer_light_tree_scene.cpp
    src/luisa/path_tracer_mesh_light_scene.cpp
    src/luisa/path_tracer_lighting.cpp
    src/luisa/path_tracer_attribute_residency.cpp
    src/luisa/path_tracer_cycles_svm_kernel_globals.cpp
    src/luisa/path_tracer_cycles_svm_scene.cpp
    src/luisa/path_tracer_cycles_svm_geometry.cpp
    src/luisa/path_tracer_cycles_svm_object.cpp
    src/luisa/path_tracer_cycles_svm_surface.cpp
    src/luisa/path_tracer_scene.cpp
    src/luisa/path_tracer_scene_upload.cpp
    src/luisa/path_tracer_displacement_plan.cpp
    src/luisa/path_tracer_displacement_scene.cpp
    src/luisa/path_tracer_scene_geometry.cpp
    src/luisa/path_tracer_tangent_space.cpp
    src/luisa/path_tracer_session.cpp
    src/luisa/path_tracer_surface_closure_evaluation.cpp
    src/luisa/path_tracer_surface_closure_sampling.cpp
    src/luisa/path_tracer_surface_closure_setup.cpp
    src/luisa/path_tracer_surface_execution_domain.cpp
    src/luisa/path_tracer_surface_route_policy.cpp
    src/luisa/path_tracer_surface_closure_decode.cpp
    src/luisa/path_tracer_surface_svm.cpp
    src/luisa/path_tracer_surface_svm_consumers.cpp
    src/luisa/path_tracer_surface_value_family.cpp
    src/luisa/path_tracer_surface_value_color_family.cpp
    src/luisa/path_tracer_surface_value_context_family.cpp
    src/luisa/path_tracer_surface_value_numeric_family.cpp
    src/luisa/path_tracer_surface_value_procedural_family.cpp
    src/luisa/path_tracer_surface_value_state_family.cpp
    src/luisa/path_tracer_surface_value_texture_family.cpp
    src/luisa/path_tracer_surface_value_runtime.cpp
    src/luisa/path_tracer_surface_value_program.cpp
    src/luisa/path_tracer_surfaces.cpp
    src/luisa/path_tracer_texture_sampling.cpp
    src/luisa/path_tracer_volume_capabilities.cpp
    src/luisa/path_tracer_volume_majorant_scene.cpp
    src/luisa/path_tracer_volume_metadata.cpp
    src/luisa/volume_guiding_filter.cpp)
